feat: add "dirty" fixes
webbhuset/elm-review-no-unqualified-functions pull request #1
Opened 2023-06-16 05:38 UTC by r-k-b

# Problem

On a huge codebase, it's a lot of work to find and fix the unqualified usages that this rule guards against.

# Solution

Supply a Fix that will qualify the usages.

Note that **the fix may have false-positives,** and add incorrect qualifications to functions or values that coincidentally have the same name as an imported function. Hence the "dirty" in the title.

Even then, implementing this dirty Fix and cleaning up the resulting errors was **much** faster than any alternative I could think of, on our 160k+ LoC project.

2023-06-16 08:42 UTC, r-k-b commented on src/NoUnqualifiedFunctions.elm
> +                           How do we tell that we shouldn't change it?
[`withModuleNameLookupTable`](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withModuleNameLookupTable) may be the answer...

2023-06-17 08:20 UTC, r-k-b commented on src/NoUnqualifiedFunctions.elm
> +                           How do we tell that we shouldn't change it?
It was! Credit to Jeroen Engels for helping out: https://elmlang.slack.com/archives/C010RT4D1PT/p1686904504914439?thread_ts=1686904175.397819&cid=C010RT4D1PT

2023-06-20 16:48 UTC, galdiuz commented
Having an automated fix sounds like a sound idea, even if it's not necessarily perfect. I'll do a review and some testing, and then I'll merge and publish.

2023-06-26 13:02 UTC, galdiuz requested changes
Looks good to me, and the fix worked in when I tested it. Clean up the comments in the code and a note in the readme about the module providing automatic fixes while mentioning `NoUnused.Variables`, then I'll merge and publish.

2023-06-26 13:02 UTC, galdiuz commented on src/NoUnqualifiedFunctions.elm
> +                                      -}
While having a fix locally in the module would be ideal, as you say `NoUnused.Variables.rule` does already handle that and that's good enough for me. Add a note in the readme about that, then remove this comment.

2023-06-26 13:02 UTC, galdiuz commented on src/NoUnqualifiedFunctions.elm
> +            -- could probably do both folds in a single pass...
It's fine this way, might be more readable even. Remove this comment.

2023-06-26 13:02 UTC, galdiuz commented on src/NoUnqualifiedFunctions.elm
> +                            [{- return only the importFix here -}]
Since we're not fixing imports, clean up these comments.

2023-07-01 01:18 UTC, r-k-b commented on src/NoUnqualifiedFunctions.elm
> +                                      -}
Sure! d69a29b1c19069a90de3456bb6fc4a6d0c390913

2023-07-01 01:18 UTC, r-k-b commented on src/NoUnqualifiedFunctions.elm
> +            -- could probably do both folds in a single pass...
e5fb33710c47821c51398c3747f0ba7e0fb7e0ca

2023-07-01 01:18 UTC, r-k-b commented on src/NoUnqualifiedFunctions.elm
> +                            [{- return only the importFix here -}]
e5fb33710c47821c51398c3747f0ba7e0fb7e0ca

2023-07-05 14:27 UTC, galdiuz approved these changes

2023-07-05 14:29 UTC, merged